### ISSUE TITLE
Realizar roteiro do vídeo de apresentação

### ISSUE THREAD

**Issue by abertanha** [abertanha/SistemaDeTarefas#13]
[Roteiro](https://docs.google.com/document/d/1Yrn7yIiyxrsrk77JS9nyJ5r1GuBTZTBxMj8Coqn1REw/edit?usp=sharing)

**Comment by clararicioni** [comment]
[Roteiro de Apresentação](https://docs.google.com/document/d/1Yrn7yIiyxrsrk77JS9nyJ5r1GuBTZTBxMj8Coqn1REw/edit?usp=sharing)
