### ISSUE TITLE
Definição de personas

### ISSUE THREAD

**Issue by clararicioni** [abertanha/SistemaDeTarefas#2]

**Comment by clararicioni** [comment]
Criar um documento usando o Google Docs sobre as personas do seu projeto.
Cada persona deve resumir as características dos usuários alvo do seu sistema.
Cada persona deve ter um ficha com as suas informações. Veja exemplos no google (imagens).

Definir de cada persona:  metas, frustrações e expectativas.

Entrega: No README.md inserir um link para o documento

Enviar o link do repositório.

Todos devem enviar.

[Figma](https://www.figma.com/design/SjRziTyrxxMfxwiJTHBQy6/Gerenciamento-de-Tarefas---ES-II?node-id=0-1&t=5er5Mlu7qrWaFttA-1) 

Links sugeridos: 
https://catarinasdesign.com.br/uso-de-personas-para-melhorar-ux-produto/
https://aconcaia.com/blog/descubra-a-importancia-das-personas-para-sua-empresa-de-software
https://you-x.eu/personas-no-desenvolvimento-de-software/

**Comment by glaucotodesco** [comment]
Usar um único template para as personas
